export const issues = [
  {
    type: 'Bug',
    id: 'PI:198700000000',
    description: 'Cluster Load Balancing',
    date: '2025/12/08',
    priority: 'Highest',
    assigned: 'Katerina larson',
    status: 'Open',
  },
  {
    type: 'Bug',
    id: 'PI:198700000001',
    description: 'Crash on File Upload',
    date: '2025/04/03',
    priority: 'Normal',
    assigned: 'Mitchell Jones',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000002',
    description: 'Database Connection Timeout',
    date: '2025/10/25',
    priority: 'Slow',
    assigned: 'Michal Marshell',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000003',
    description: 'Memory Leak in Module X',
    date: '2025/11/19',
    priority: 'High',
    assigned: 'Tiger Nixon',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000004',
    description: 'Slow Response Time on API Calls',
    date: '2025/09/29',
    priority: 'Highest',
    assigned: 'Jamie Smith',
    status: 'On Hold',
  },
  {
    type: 'Bug',
    id: 'PI:198700000005',
    description: 'File Permission Denied Error',
    date: '2025/05/11',
    priority: 'Slow',
    assigned: 'Mitchell Jones',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000006',
    description: 'Server Rendering Bug',
    date: '2025/06/05',
    priority: 'Highest',
    assigned: 'Mitchell Jones',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000007',
    description: 'Error Logging Not Working',
    date: '2025/07/06',
    priority: 'Normal',
    assigned: 'Tiger Nixon',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000008',
    description: 'Database Connection Timeout',
    date: '2025/02/10',
    priority: 'Normal',
    assigned: 'Tiger Nixon',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000009',
    description: 'Unexpected Logout on Session Timeout',
    date: '2025/12/18',
    priority: 'Highest',
    assigned: 'Jamie Smith',
    status: 'On Hold',
  },
  {
    type: 'Bug',
    id: 'PI:198700000010',
    description: 'Cache Invalidation Problem',
    date: '2025/04/03',
    priority: 'Slow',
    assigned: 'Jamie Smith',
    status: 'On Hold',
  },
  {
    type: 'Bug',
    id: 'PI:198700000011',
    description: 'Cluster Load Balancing',
    date: '2025/11/12',
    priority: 'Highest',
    assigned: 'Alex Morgan',
    status: 'Open',
  },
  {
    type: 'Bug',
    id: 'PI:198700000012',
    description: 'Data Mirroring Error',
    date: '2025/06/26',
    priority: 'Slow',
    assigned: 'Mitchell Jones',
    status: 'On Hold',
  },
  {
    type: 'Bug',
    id: 'PI:198700000013',
    description: 'Unexpected Logout on Session Timeout',
    date: '2025/11/08',
    priority: 'High',
    assigned: 'Alex Morgan',
    status: 'Open',
  },
  {
    type: 'Bug',
    id: 'PI:198700000014',
    description: 'Authentication Token Expiry Issue',
    date: '2025/09/22',
    priority: 'Normal',
    assigned: 'Alex Morgan',
    status: 'On Hold',
  },
  {
    type: 'Bug',
    id: 'PI:198700000015',
    description: 'Crash on File Upload',
    date: '2025/11/14',
    priority: 'Highest',
    assigned: 'Tiger Nixon',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000016',
    description: 'Authentication Token Expiry Issue',
    date: '2025/04/14',
    priority: 'Highest',
    assigned: 'Michal Marshell',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000017',
    description: 'Error Logging Not Working',
    date: '2025/11/16',
    priority: 'Highest',
    assigned: 'Michal Marshell',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000018',
    description: 'UI Misalignment in Mobile View',
    date: '2025/04/16',
    priority: 'Normal',
    assigned: 'Jamie Smith',
    status: 'Open',
  },
  {
    type: 'Bug',
    id: 'PI:198700000019',
    description: 'Crash on File Upload',
    date: '2025/08/15',
    priority: 'High',
    assigned: 'Alex Morgan',
    status: 'Open',
  },
  {
    type: 'Bug',
    id: 'PI:198700000020',
    description: 'Cluster Load Balancing',
    date: '2025/06/12',
    priority: 'Slow',
    assigned: 'Michal Marshell',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000021',
    description: 'Cluster Load Balancing',
    date: '2025/12/04',
    priority: 'High',
    assigned: 'Katerina larson',
    status: 'On Hold',
  },
  {
    type: 'Bug',
    id: 'PI:198700000022',
    description: 'Unexpected Logout on Session Timeout',
    date: '2025/06/01',
    priority: 'Highest',
    assigned: 'Tiger Nixon',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000023',
    description: 'Software Run Failure',
    date: '2025/03/26',
    priority: 'High',
    assigned: 'Mitchell Jones',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000024',
    description: 'Slow Response Time on API Calls',
    date: '2025/07/31',
    priority: 'Normal',
    assigned: 'Katerina larson',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000025',
    description: 'Memory Leak in Module X',
    date: '2025/11/04',
    priority: 'High',
    assigned: 'Mitchell Jones',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000026',
    description: 'Data Mirroring Error',
    date: '2025/03/03',
    priority: 'Highest',
    assigned: 'Michal Marshell',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000027',
    description: 'Slow Response Time on API Calls',
    date: '2025/06/13',
    priority: 'Slow',
    assigned: 'Mitchell Jones',
    status: 'On Hold',
  },
  {
    type: 'Bug',
    id: 'PI:198700000028',
    description: 'UI Misalignment in Mobile View',
    date: '2025/06/02',
    priority: 'Highest',
    assigned: 'Jamie Smith',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000029',
    description: 'File Permission Denied Error',
    date: '2025/07/20',
    priority: 'High',
    assigned: 'Alex Morgan',
    status: 'Open',
  },
  {
    type: 'Bug',
    id: 'PI:198700000030',
    description: 'Server Rendering Bug',
    date: '2025/04/04',
    priority: 'Normal',
    assigned: 'Mitchell Jones',
    status: 'Open',
  },
  {
    type: 'Bug',
    id: 'PI:198700000031',
    description: 'Software Run Failure',
    date: '2025/03/01',
    priority: 'High',
    assigned: 'Alex Morgan',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000032',
    description: 'Cache Invalidation Problem',
    date: '2025/10/13',
    priority: 'Normal',
    assigned: 'Michal Marshell',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000033',
    description: 'Cluster Load Balancing',
    date: '2025/05/03',
    priority: 'Slow',
    assigned: 'Alex Morgan',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000034',
    description: 'File Permission Denied Error',
    date: '2025/01/04',
    priority: 'Highest',
    assigned: 'Mitchell Jones',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000035',
    description: 'Server Rendering Bug',
    date: '2025/12/18',
    priority: 'High',
    assigned: 'Tiger Nixon',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000036',
    description: 'UI Misalignment in Mobile View',
    date: '2025/10/09',
    priority: 'High',
    assigned: 'Jamie Smith',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000037',
    description: 'Data Mirroring Error',
    date: '2025/07/29',
    priority: 'Slow',
    assigned: 'Alex Morgan',
    status: 'Close',
  },
  {
    type: 'Bug',
    id: 'PI:198700000038',
    description: 'Cluster Load Balancing',
    date: '2025/06/13',
    priority: 'Slow',
    assigned: 'Jamie Smith',
    status: 'Pending',
  },
  {
    type: 'Bug',
    id: 'PI:198700000039',
    description: 'Unexpected Logout on Session Timeout',
    date: '2025/10/28',
    priority: 'Slow',
    assigned: 'Michal Marshell',
    status: 'On Hold',
  },
];
